### ISSUE TITLE
Downgrade Jekyll

### ISSUE THREAD

**Issue by ghost** [jsturtevant/jekyll-vagrant#3]
Jekyll 3.1.6, provided by default, doesn't work for us. Most of us use Jekyll 2.4. Please tell me exactly how to downgrade on Windows 7.

I tried `gem jekyll uninstall` followed by `gem install jekyll -v 2.4.0` but then Jekyll wouldn't build. Apparently, bundler isn't installed, would not install as the `vagrant` user but when I tried to install bundler as `root`, still didn't fix the issue.

Please provide the exact steps. I tried googling with little luck.

**Comment by jsturtevant** [comment]
The [provided script](https://github.com/jsturtevant/jekyll-vagrant/blob/master/bootstrap.sh) uses github's pages [gem package](https://github.com/github/pages-gem) to install all the [dependencies](https://pages.github.com/versions/).

To use a different version of the package for jekyll 2.4 change the script to call version 43 (the last version to include [jekyll 2.4](https://rubygems.org/gems/github-pages/versions/43)):

```
gem install github-pages -v 43
```

**Comment by ghost** [comment]
Thanks. Closing.
