### ISSUE TITLE
Vagrant/Jekyll and symlinks

### ISSUE THREAD

**Issue by ghost** [jsturtevant/jekyll-vagrant#4]
Windows 7, Virtual Box 5.0.20, cloned your site the other day but using a modified `Vagrantfile`.

Casting about for ideas. To avoid copying .md files that haven't changed between releases for our documentation site, we're using symlinks to represent them. IOW, the 2.0 directory might have `mytopic.md` and if that topic hasn't changed in 2.1, it's represented in that directory with a symlink to the 2.0 directory.

On Windows, Jekyll simply copies the `.md` files from `_site/2.0` to `_site/2.1`. Mac does the right thing by rendering the symlink as `.html`.

Thoughts?

`Vagrantfile`

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME="magento-devdocs"
HOST_PORT="4000"
RAM="1024"
CPU="50"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = NAME
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: "4000", host: HOST_PORT
  config.vm.synced_folder "../.", "/jekyll/devdocs"
  config.vm.provider "virtualbox" do |v|
    v.customize ['modifyvm', :id, '--name', NAME, '--memory', RAM, "--cpuexecutioncap", CPU]
  end
end
```

`bootstrap.sh`

```
#!/usr/bin/env bash

# Customization parameters
RUBY_VERSION=2.2
RVM_PATH=/usr/local/rvm
GEMS=bundler

# Get information on the newest versions of Ubuntu packages
sudo apt-get update

# Install Ubuntu packages
sudo apt-get install nodejs -y

# Install Ruby
if [ ! -e $RVM_PATH ]; then
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    curl -sSL https://get.rvm.io | bash -s
fi

source $RVM_PATH/scripts/rvm

rvm use --install $RUBY_VERSION --default

# Install gems
gem install $GEMS

# Clean up
sudo apt-get autoremove -y

# Install gems and dependencies from Gemfile
cd /jekyll/devdocs
bundle install

# Run devdocs in Jekyll
cd /jekyll/devdocs && bundle exec jekyll serve --host=0.0.0.0
```

**Comment by ghost** [comment]
I'm sorry for using your issues to think out loud but maybe this will help someone else.

This issue is apparently caused by using the Windows Git Bash client to clone the repository. When I shell into Vagrant, the files aren't seen as symlinks. If I have a real problem getting this to work I'll post it on another forum.

**Comment by jsturtevant** [comment]
if you get it working post the answer here or a link so other will be able to track back if they do land here.  Thanks and good luck!

**Comment by ghost** [comment]
**EDIT**

This is a [good explanation](http://blog.rudylee.com/2014/10/27/symbolic-links-with-vagrant-windows/) of the problem and workaround.

In our case, we have Markdown files in a 2.0 and 2.1 directory. Any file that's identical in both is represented in the 2.1 directory by a symlink. I cloned the GitHub repository, ran `vagrant up` with the workaround but discovered none of the symlinks were there anymore. They were all ordinary files with binary content.

I noticed though that I could _create new_ symlinks.

_New info_: On Windows, several Git commands (including `git commit`, `git checkout`, and `git status`) falsely show that all the symlinks are modified. As long as you're working in the container, it's safe to use Git and a text editor (I've used Sublime) to edit as normal. Only the files you change are committed. It's confusing and if anyone knows a way around it, please let me know.

All's well.
